select_origin: directory
files_origin: "./fiches"
nodes_origin: ""
links_origin: ""
nodes_online: ""
links_online: ""
images_origin: ""
export_target: "./export/"
history: false
focus_max: 2
record_types:
  undefined:
    fill: "#a7a0a0"
    stroke: "#a7a0a0"
  algorithme:
    fill: "#6a4c93"
    stroke: "#6a4c93"
  concept:
    fill: "#1982c4"
    stroke: "#1982c4"
  professionnel:
    fill: "#ff8e38"
    stroke: "#ff8e38"
  techniques:
    fill: "#8ac927"
    stroke: "#8ac927"
  méthodes:
    fill: "#59cf92"
    stroke: "#59cf92"
  investigations:
    fill: "#ef1f1f"
    stroke: "#ef1f1f"
  organisation:
    fill: "#f36d9c"
    stroke: "#f36d9c"
link_types:
  undefined:
    stroke: simple
    color: "#e1e1e1"
  o:
    stroke: simple
    color: "#e01f1f"
  g:
    stroke: simple
    color: "#000000"
record_filters: []
graph_background_color: "#ffffff"
graph_highlight_color: "#ff6a6a"
graph_highlight_on_hover: true
graph_text_size: 6
graph_arrows: true
node_size_method: degree
node_size: 10
node_size_max: 10
node_size_min: 2
attraction_force: 75
attraction_distance_max: 250
attraction_vertical: 0.1
attraction_horizontal: 0.1
views: {}
chronological_record_meta: created
css_custom: "./algoj.css"
record_metas: []
title: "AlgoJ"
author: "Olivier Le Deuff, Rayya Roumanos"
description: "Mené par l'Institut de Journalisme Bordeaux Montaigne (IJBA) et le laboratoire MICA en partenariat avec Sud Ouest et Curieux!, le projet Algo-J entend étudier la place et le rôle des algorithmes numériques dans le secteur de la presse. Il est porté par Rayya Roumanos et Olivier Le Deuff et s’appuie sur une équipe pluridisciplinaire composée d’Arnaud Schwartz, Florian Tixier, Ugo Verdi et Mohamed Mosbah. L’enquête comprend trois visées qui répondent aux multiples enjeux de la présence massive et structurante des algorithmes dans l’écosystème informationnel. Celle, d’abord, d’étudier l’influence de ces actants technologiques sur les écritures journalistiques. Celle, ensuite, de mesurer le niveau d’acculturation des journalistes à la logique algorithmique qui charpente leurs horizons de production de l’information. Et celle, enfin, de mettre en œuvre une méthodologie à mi-chemin entre l’exploration scientifique et l’investigation journalistique pour enquêter sur les algorithmes. Ces fiches dédiées à la thématique algorithmique ont été réalisées par l'équipe après un premier travail exploratoire d’Emma Rondot, étudiante en master à l’IJBA."
keywords: []
link_symbol: →
devtools: false
lang: fr
